name: Update

on:
  push:
    branches: [master]
  fork:
  watch:
    types: [started]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        uses: ouuan/This-repo-has-x-stars-y-forks-action@master
        with:
          token: ${{ secrets.TOKEN }}
          template: "A GitHub Action to update this sentence for your repository: <star-fork>."
