name: Update

on:
  push:
    branches: main
  schedule:
    - cron: "5 * * * *"
  fork:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Update
        run: node ./src/main.js
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
